### ISSUE TITLE
Can you provide a trained model checkpoint?

### ISSUE THREAD

**Issue by zmykevin** [alasdairtran/transform-and-tell#14]
Hi Alasdair,
Thank you for sharing the code about your great work! I am interested to play with your a trained news caption model for my own project and I wonder if you can share a trained checkpoint. 
Thanks in advance and I am looking forward to hearing your reply. 
Best,
Mingyang

**Comment by alasdairtran** [comment]
If you just need the checkpoints, here they are:

https://cloudstor.aarnet.edu.au/plus/s/vsN51Y9Dh4eww39

See the README file for more info on the different model variants.

**Comment by YcZhangSing** [comment]
Hello Dr.Alasdair, this link is lost, could you please provide another available one? Thanks!

**Comment by alasdairtran** [comment]
> Hello Dr.Alasdair, this link is lost, could you please provide another available one? Thanks!

You can request the dataset by sending me an email (email is in README file).
