### ISSUE TITLE
Run your model on a single new piece of news

### ISSUE THREAD

**Issue by zmykevin** [alasdairtran/transform-and-tell#18]
Hi Tran, 
Thank you for making this cool project available! I notice that on the demo, you have allow users to provide a single link of a new piece of news and generate the caption accordingly.  I wonder if you also have a script in this github repo that allows us to use your pre-trained model to generate a caption for one new news sample? Thanks!

**Comment by alasdairtran** [comment]
I haven't written up a self-contained script to generate a caption from arbitrary input yet. But that's a good idea - I'll put it on my to-dos.

In the meantime, all of the demo app code is included in the repo [here](https://github.com/alasdairtran/transform-and-tell/tree/master/demo). The backend object that's responsible for generating the caption is [here](https://github.com/alasdairtran/transform-and-tell/blob/master/tell/tasks/captioner.py). You probably can clean up that file a bit to make it self-contained. Basically when we query the backend, the method `CaptioningWorker.generate_captions(articles)` in that file is called and it returns generated captions.

**Comment by zmykevin** [comment]
That is very helpful! I am actually already working on writing up a full pipeline to process a single source of news with all the input information in a json format. If I make it work, I will let you know~
